version: "3"

services:
  ombi:
    privileged: true
    image: linuxserver/ombi
    container_name: ombi
    restart: always
    environment:
      TZ: UTC # TODO: Set to local timezone
    volumes:
      - ./config:/config
    ports:
      - 3579:3579

    healthcheck:
      test: curl --fail -s http://localhost:3579/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
