version: "3"

services:
  sonarr:
    privileged: true
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
      PGID: 0
      PUID: 0
    volumes:
      - ./config:/config
      - ../data/tv:/tv
      - ../data/downloads:/downloads
    ports:
      - 8988:8989

    healthcheck:
      test: curl --fail -s http://localhost:8988/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
