version: "3"

services:
  bazarr:
    privileged: true
    image: linuxserver/bazarr
    container_name: bazarr
    restart: always
    environment:
      TZ: UTC # TODO: set to local timezone
      PGID: 0
      PUID: 0
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /nas:/nas       # TODO: Map in your Media Shares Below...
    ports:
      - 6767:6767

    healthcheck:
      test: curl --fail -s http://localhost:6767/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
