version: "3"

services:
  qbittorrent:
    privileged: true
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
      PGID: 0
      PUID: 0
      WEBUI_PORT: 8080
      UMASK_SET: 022
    volumes:
      - ./config:/config
      - ../data/qbittorent:/downloads
    networks:
      - media-proxy
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp

    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  media-proxy:
    driver: bridge
    external: true
