version: "3"

services:
  ombi:
    privileged: true
    image: linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
      PGID: 0
      PUID: 0
      # BASE_URL: /ombi
    volumes:
      - ./config:/config
    networks:
      - media-proxy
    ports:
      - 3579:3579

    healthcheck:
      test: curl --fail -s http://localhost:3579/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  media-proxy:
    driver: bridge
    external: true
