version: "3"

services:
  radarr:
    privileged: true
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
      PGID: 0
      PUID: 0
    volumes:
      - ./config:/config
      - ../data/movies:/movies
      - ../data/downloads:/downloads
    ports:
      - 7878:7878

    healthcheck:
      test: curl --fail -s http://localhost:7878/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
