version: "3"

services:
  qbittorrent:
    privileged: true
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: always
    environment:
      TZ: UTC # TODO: set to local timezone
      WEBUI_PORT: 8080
      PUID: 0
      PGID: 0
      UMASK_SET: 022
    volumes:
      - ./config:/config
      - /nas:/nas # TODO: Map in the volumes where you would like to save your torrent files...
    ports:
      - 8080:8080
      - 18999:18999/udp
      - 18999:18999

    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
