version: "3"

services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
      PGID: 0
      PUID: 0
    volumes:
      - ./config:/config
      - ../data/blackhole:/downloads
    networks:
      - media-proxy
    ports:
      - 9117:9117

    healthcheck:
      test: curl --fail -s http://localhost:9117/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  media-proxy:
    driver: bridge
    external: true
