version: "3"

services:
  jackett:
    privileged: true
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /nzbget-downloads/jackett-blackhole:/downloads      # TODO: Configure to point to your mapped "blackhole" directory
    ports:
      - 9117:9117

    healthcheck:
      test: curl --fail -s http://localhost:9117/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
