version: "3"

services:
  bazarr:
    privileged: true
    image: linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
      PGID: 0
      PUID: 0
    volumes:
      - ./config:/config
      - ../data/movies:/movies
      - ../data/tv:/tv
    ports:
      - 6767:6767

    healthcheck:
      test: curl --fail -s http://localhost:6767/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
