version: "3"

services:
  radarr:
    privileged: true
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    environment:
      TZ: UTC # TODO: set to local timezone
      PUID: 0
      PGID: 0
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /nas:/nas # TODO: fix path

      # Volumes for post-processing
      - /var/run/docker.sock:/var/run/docker.sock
      - ./pp-scripts:/opt/pp-scripts
    ports:
      - 7878:7878

    healthcheck:
      test: curl --fail -s http://localhost:7878/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
