version: "3"

services:
  sonarr:
    privileged: true
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    environment:
      TZ: UTC # TODO: set to local timezone
      PUID: 0
      PGID: 0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /nas:/nas       # TODO: Map in your Media Shares & Download Client's Share(s)...
    ports:
      - 8988:8989

    healthcheck:
      test: curl --fail -s http://localhost:8988/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
